name: Merge develop into components
on: 
  schedule:
    - cron:  '0 13 * * 5'
  workflow_dispatch:

jobs:
  merge_develop_club_integrations:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Sends a Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: merge-develop-test
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_LINK_NAMES: true
        SLACK_MESSAGE: 'Post Content :rocket: <@U01R5DNGLS1>'
        SLACK_ICON: https://github.com/golfgenius/golfgenius/blob/master/app/assets/images/home/logos/ggs.png
        SLACK_TITLE: Message
        SLACK_USERNAME: Golf Genius
#   merge_develop_club:
#     runs-on: ubuntu-latest
#     steps:

#   merge_develop_usga_associations:
#     runs-on: ubuntu-latest
#     steps:

#   merge_develop_golf_canada:
#     runs-on: ubuntu-latest
#     steps:

#   merge_develop_gg_associations:
#     runs-on: ubuntu-latest
#     steps:

#   merge_develop_international:
#     runs-on: ubuntu-latest
#     steps:

#   merge_develop_pga_pro:
#     runs-on: ubuntu-latest
#     steps:

#   merge_develop_usability:
#     runs-on: ubuntu-latest
#     steps:

#   merge_develop_internal:
#     runs-on: ubuntu-latest
#     steps:
